highlighter: rouge

title: Kevin Reed

url: https://kevinareed.com
description: Full stack software developer. These are my thoughts on Javascript, .NET, DevOps, and other web development topics.
permalink: /:year/:month/:day/:title/

author:
    name: Kevin Reed
    email: kevin.a.reed@gmail.com
    github: kavun
    twitter: kavun
    gravatar: http://www.gravatar.com/avatar/7a50e2c54da24204ab31432a721aa215.png

analytics:
    provider: google
    google:
        tracking_id: 'UA-41550976-1'
        domain: 'kevinareed.com'
